### ISSUE TITLE
Invalid strings when opening LiVES 3.0.2 under Xubuntu 20.04

### ISSUE THREAD

**Issue by Guybrush88** [salsaman/LiVES#10]
When opening LiVES 3.0.2 under Xubuntu 20.04, I get these error messages:

(lives-exe:10106): Gtk-WARNING **: 09:37:19.310: Invalid input string

(lives-exe:10106): Gtk-WARNING **: 09:37:19.310: Invalid input string

(lives-exe:10106): Pango-WARNING **: 09:37:19.321: Invalid UTF-8 string passed to pango_layout_set_text()

(lives-exe:10106): Gtk-WARNING **: 09:37:19.341: Invalid input string

(lives-exe:10106): Gtk-WARNING **: 09:37:19.364: Invalid input string

(lives-exe:10106): Gtk-WARNING **: 09:37:19.364: Invalid input string

(lives-exe:10106): Pango-WARNING **: 09:37:19.369: Invalid UTF-8 string passed to pango_layout_set_text()

(lives-exe:10106): Pango-WARNING **: 09:37:19.374: Invalid UTF-8 string passed to pango_layout_set_text()

(lives-exe:10106): Gtk-WARNING **: 09:37:19.375: Invalid input string

(lives-exe:10106): Pango-WARNING **: 09:37:19.394: Invalid UTF-8 string passed to pango_layout_set_text()

**Comment by salsaman** [comment]
Can you check with the current git version and see if it still happens ?

**Comment by Guybrush88** [comment]
how can I download that? I actually never used that feature for softwares from github, so I guess I'm not really aware about such feature

**Comment by salsaman** [comment]
There is a link on the github page where you can download a zip file of the current source, or make a local clone of the repository.
Also: http://lives-video.com/index.php?do=code

**Comment by Guybrush88** [comment]
thanks, I'm going to test soon and report the results
