### ISSUE TITLE
3.2.0 compile error on Ubuntu 20.04

### ISSUE THREAD

**Issue by PandaJim** [salsaman/LiVES#24]
jack.c: In function ‘lives_jack_init’:
jack.c:124:10: warning: implicit declaration of function ‘jackctl_server_open’; did you mean ‘jackctl_server_stop’? [-Wimplicit-function-declaration]
  124 |     if (!jackctl_server_open(jackserver, driver)) {
      |          ^~~~~~~~~~~~~~~~~~~
      |          jackctl_server_stop
jack.c:129:10: error: too few arguments to function ‘jackctl_server_start’
  129 |     if (!jackctl_server_start(jackserver)) {
      |          ^~~~~~~~~~~~~~~~~~~~
In file included from jack.h:17,
                 from main.h:1116,
                 from jack.c:7:
/usr/include/jack/control.h:144:1: note: declared here
  144 | jackctl_server_start(
      | ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1184: jack.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src'
make[1]: *** [Makefile:651: all-recursive] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j4 returned exit code 2
make: *** [debian/rules:7: build] Error 25

**Comment by salsaman** [comment]
Works for me with libjack-jackd2-dev	1.9.14-0ubuntu2

**Comment by PandaJim** [comment]
Great, it works by using libjack-jackd2-dev instead of libjack-dev

**Comment by salsaman** [comment]
BTW, the recommendation now is to package libweed / libweed-dev separately and make it a dependency.

**Comment by VVD** [comment]
Did you dropped support of jack1 completely?

**Comment by salsaman** [comment]
https://github.com/jackaudio/jackaudio.github.com/wiki/Differences-between-jack1-and-jack2

"Use JACK2, as that is one being actively worked on and maintained."

**Comment by salsaman** [comment]
[jack1.txt](https://github.com/salsaman/LiVES/files/5539789/jack1.txt)

Patch for jack1.

**Comment by VVD** [comment]
Thanks!
It build with jack1 now!
