### ISSUE TITLE
build error on Ubuntu 20.10 with glibc 2.32

### ISSUE THREAD

**Issue by PandaJim** [salsaman/LiVES#25]
In Ubuntu 20.10 libc6-dev has dropped /usr/include/rpc/rpc.h which causes build errors:

 ```
htmsocket.c:41:10: fatal error: rpc/rpc.h: No such file or directory
   41 | #include <rpc/rpc.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:610: sendOSC-htmsocket.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/<<PKGBUILDDIR>>/libOSC/sendOSC'
make[2]: *** [Makefile:798: all-recursive] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/libOSC'
make[1]: *** [Makefile:651: all-recursive] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j4 returned exit code 2
make: *** [debian/rules:7: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by salsaman** [comment]
I think it should be possible to remove the line:
#include <rpc/rpc.h>
from libOSC/sendOSC/htmsocket.c
as it appears that the header is no longer required.

**Comment by salsaman** [comment]
I think probably at some point there were functions that needed it, but these  have since been removed / replaced.
The similar file src/htmsocket.c does not include rpc.h, and the quick test I did just now to remove it from libOSC did not produce any warnings or errors.

So it seems like a safe bet to just remove the line altogether.

**Comment by salsaman** [comment]
If you can confirm that it resolves the issue then I will add it as a "release note".

**Comment by PandaJim** [comment]
I'm just building the package for Ubuntu, but not an editor. And build without "#include <rpc/rpc.h>" succeeded
