### ISSUE TITLE
3.2.0 release build fails with --enable-toonz

### ISSUE THREAD

**Issue by rezso** [salsaman/LiVES#26]
toonz.cpp: In function ‘weed_error_t common_process(weed_plant_t*, weed_timecode_t, int)’:
toonz.cpp:674:7: warning: unused variable ‘error’ [-Wunused-variable]
  674 |   int error;
      |       ^~~~~
toonz.cpp: In function ‘weed_plant_t* weed_setup(weed_bootstrap_f)’:
toonz.cpp:858:91: error: too many arguments to function ‘weed_plant_t* weed_channel_template_init(const char*, int)’
  858 |   weed_plant_t *in_chantmpls[] = {weed_channel_template_init("in channel", 0, palette_list), NULL};
      |                                                                                           ^
In file included from toonz.cpp:58:
weed-plugin-utils.c:238:22: note: declared here
  238 | static weed_plant_t *weed_channel_template_init(const char *name, int flags) {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
toonz.cpp:859:93: error: too many arguments to function ‘weed_plant_t* weed_channel_template_init(const char*, int)’
  859 |   weed_plant_t *out_chantmpls[] = {weed_channel_template_init("out channel", 0, palette_list), NULL};
      |                                                                                             ^
In file included from toonz.cpp:58:
weed-plugin-utils.c:238:22: note: declared here
  238 | static weed_plant_t *weed_channel_template_init(const char *name, int flags) {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
toonz.cpp: In instantiation of ‘int paraffin_kernel(cv::Mat&, cv::Mat&, int, weed_plant_t**) [with VecT = cv::Vec<unsigned char, 4>; weed_plant_t = _weed_leaf]’:
toonz.cpp:737:65:   required from here
toonz.cpp:579:7: warning: unused variable ‘error’ [-Wunused-variable]
  579 |   int error;
      |       ^~~~~
toonz.cpp: In instantiation of ‘int paraffin_kernel(cv::Mat&, cv::Mat&, int, weed_plant_t**) [with VecT = cv::Vec<unsigned char, 3>; weed_plant_t = _weed_leaf]’:
toonz.cpp:739:65:   required from here
toonz.cpp:579:7: warning: unused variable ‘error’ [-Wunused-variable]

**Comment by salsaman** [comment]
Thanks. f1918fe00a774b1ab68b2659df4523b6c2db868a should fix the compilation issues.

**Comment by rezso** [comment]
Sorry for the late reply.
https://github.com/salsaman/LiVES/commit/f1918fe00a774b1ab68b2659df4523b6c2db868a requires iostream:

toonz.cpp: In function ‘int cnoise_compute(cv::Mat&, weed_plant_t**, double)’:
toonz.cpp:130:29: error: ‘cerr’ is not a member of ‘std’
  130 | #define DEBUG_PRINT(a) std::cerr << a << std::endl;
      |                             ^~~~
toonz.cpp:813:5: note: in expansion of macro ‘DEBUG_PRINT’
  813 |     DEBUG_PRINT(e.what());
      |     ^~~~~~~~~~~
toonz.cpp:127:1: note: ‘std::cerr’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
  126 | #include "opencv2/imgproc/imgproc.hpp"
  +++ |+#include <iostream>
  127 | 
make[3]: *** [Makefile:1686: toonz_la-toonz.lo] Error 1

After adding iostream to included headers, the build is successful.

**Comment by salsaman** [comment]
Thanks. Added in 229b1ab762c3e7ca3437573e94e555e3ef20cbd5 and closing as fixed.
