### ISSUE TITLE
Audio backend default on FreeBSD should be OSS, and OSS should be in the list if audio backend options

### ISSUE THREAD

**Issue by yurivict** [salsaman/LiVES#29]
In the other issue you said:

> [...] "alsa" is hardcoded as the default driver name (except for SOLARIS which uses "oss" and DARWIN which uses "coreaudio", and the mingw version will use "portaudio" IIRC). 

FreeBSD should also have OSS as default.

Additionally, OSS should be an audio backend option, which is it currently not on FreeBSD.

**Comment by salsaman** [comment]
OSS will be made available as a selectable jack driver. This is being done as part of
https://github.com/salsaman/LiVES/issues/28

Closing this as a duplicate. Any relevant comments should be added in the other issue.

**Comment by yurivict** [comment]
So it has to go through Jack, and can't just use OSS directly?
