### ISSUE TITLE
Can't build Release 3.0.1 on Debian 10

### ISSUE THREAD

**Issue by Swiftb0y** [salsaman/LiVES#3]
Hey, I'm very interested in your project but I have issues building the latest release.
First of our install instructions are a bit out-of-date. You are saying to execute `configure` directly. However, `autogen.sh` has to be run before to actually generate `configure`. But my actual issue is that `autogen.sh` fails as well:
```
Preparing the LiVES build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.16.1
Found GNU Libtool version 2.4.6

Automatically preparing build ... Warning: autoreconf failed
Attempting to run the preparation steps individually

Preparing build ... 
Warning:  Unsupported macros were found in ./configure.ac

The configure.ac file was scanned in order to determine if any
unsupported macros are used that exceed the minimum version
settings specified within this file.  As such, the following macros
should be removed from configure.ac or the version numbers in this
file should be increased:

AC_GNU_SOURCE

Ignorantly continuing build preparation ... 
Warning: autoconf seems to have succeeded by removing the following options:
	AUTOCONF_OPTIONS="-f"

Removing those options should not be necessary and indicate some other
problem with the build system.  The build preparation is highly suspect
and may result in configuration or compilation errors.  Consider
rerunning the build preparation with verbose output enabled.
	./autogen.sh --verbose

Continuing build preparation ... configure.ac:935: error: required file 'intl/Makefile.in' not found
Makefile.am:35: error: required directory ./intl does not exist
ERROR: automake failed
```

**Comment by salsaman** [comment]
Hi,
running autogen.sh should only be necessary if you check out the code from git. If you are building from a source release then you should only need to run configure.

It seems like AC_GNU_SOURCE is now obsolete; this needs to be replaced with AC_USE_SYSTEM_EXTENSIONS in configure.ac. I will update this in git.

./intl should be created by autoreconf -i, which is normally run as part of the autogen.sh process. 
It may be that due to the prior warning this is not being run in your case.

You can try amending configure.ac as noted, and then running ./autogen.sh --verbose as recommended. You should see it running autoreconf and generating ./intl.

Alternately you can download a release file (.tar.bz2 or .gz) and then simply run ./configure and make install.

**Comment by Swiftb0y** [comment]
I tried the release file (because I have some issues installing the dependencies for compiling the code  from the repository) but as I noted previously, there is no `configure` script present in any of the release versions.

**Comment by salsaman** [comment]
Sure there is ! http://lives-video.com/releases/LiVES-3.0.1.tar.bz2 for example has the configure script included.

**Comment by Swiftb0y** [comment]
Ahh, yes these include them. I was using the github releases. Thanks for your help.

**Comment by salsaman** [comment]
For debian there is also:
https://packages.debian.org/sid/lives

**Comment by Swiftb0y** [comment]
Yes, but as I've outlined previously, I'm using buster, which has not been updated: https://packages.debian.org/buster/lives

**Comment by Swiftb0y** [comment]
Unfortunately I still can't build it fully. It fails at `po`
```
Making install in po
make[1]: Entering directory '/home/swiftb0y/Sourcerepositories/lives-3.0.1/po'
test ! -f ./lives.pot || \
  test -z "ar.gmo fr.gmo ca.gmo cs.gmo da.gmo ja.gmo nl_NL.gmo de_DE.gmo pt.gmo pt_BR.gmo hu.gmo es.gmo it.gmo pl.gmo tr.gmo ru.gmo zh_CN.gmo sk.gmo he.gmo en_GB.gmo fi.gmo et.gmo gl.gmo uz.gmo te.gmo ro.gmo uk.gmo oc.gmo hr.gmo ug.gmo pms.gmo" || make ar.gmo fr.gmo ca.gmo cs.gmo da.gmo ja.gmo nl_NL.gmo de_DE.gmo pt.gmo pt_BR.gmo hu.gmo es.gmo it.gmo pl.gmo tr.gmo ru.gmo zh_CN.gmo sk.gmo he.gmo en_GB.gmo fi.gmo et.gmo gl.gmo uz.gmo te.gmo ro.gmo uk.gmo oc.gmo hr.gmo ug.gmo pms.gmo
make[2]: Entering directory '/home/swiftb0y/Sourcerepositories/lives-3.0.1/po'
rm -f ar.gmo && : -c --statistics -o ar.gmo ar.po
mv: cannot stat 't-ar.gmo': No such file or directory
make[2]: *** [Makefile:148: ar.gmo] Error 1
make[2]: Leaving directory '/home/swiftb0y/Sourcerepositories/lives-3.0.1/po'
make[1]: *** [Makefile:185: stamp-po] Error 2
make[1]: Leaving directory '/home/swiftb0y/Sourcerepositories/lives-3.0.1/po'
make: *** [Makefile:647: install-recursive] Error 1
```

**Comment by salsaman** [comment]
Looks like either you don't have gettext installed or it is broken on your system.
You can either install / fix gettext or run ./configure --disable-nls

**Comment by Swiftb0y** [comment]
I thought I had it installed. But a simple `apt-get install gettext` solved it. Thank you.
