### ISSUE TITLE
smogrify fails due to perl not have threads support

### ISSUE THREAD

**Issue by bkauler** [salsaman/LiVES#43]
In EasyOS, perl is compiled without threads support. This causes smogrify to fail.

According to this link, most distributions ship with perl not compiled with threading support:

https://newbedev.com/why-is-perl-usually-installed-without-thread-support

I ran "perl -V" to confirm that indeed, no ithread support. A bit of research, need "-Dusethreads" when compile perl. But, the above link recommends not to, and it has never been a problem before.

Is it possible to run smogrify without perl threads? Or, do I have to recompile perl?

**Comment by bkauler** [comment]
This is output in a terminal:

```
# lives
This Perl not built to support threads
Compilation failed in require at /usr/bin/smogrify line 35.
BEGIN failed--compilation aborted at /usr/bin/smogrify line 35.
LIVES FATAL: 
`smogrify` must be in your path, and be executable
```
I commented out these lines, and it starts up:

```
use Config;
my $hasthreads = 0;
#if ($Config{useithreads}) {
#    $hasthreads = 1;
#    use threads;
#}
```

**Comment by bkauler** [comment]
Well, tries to start, see issue #44

**Comment by salsaman** [comment]
Yes, actually I can remove that requirement, it's only used for testing, but as the comment says:

 ## test with threading - although it doesn't really seem any faster

will update in github
