### ISSUE TITLE
Startup checks fail

### ISSUE THREAD

**Issue by juanitotc** [salsaman/LiVES#45]
Lives start-up checks fail:

If mpv is present, but not mplayer the check will fail
If mplayer and mpv are present, it only checks if mplayer can convert to png
(sox was not present0

![lives_error](https://user-images.githubusercontent.com/11058217/147854222-e78257f6-da0c-426f-90f6-0877a4ad03f9.png)

**Comment by juanitotc** [comment]
Ah - the other tests fail if sox is not present - OK now

**Comment by salsaman** [comment]
Not sure, what is happening here...sox being present is highly recommended (still used to convert some external audio formats), but if not it will fall back to a limited functionality using mplayer/mplayer2/mpv. Also sox / mplayer at one time could be used as the audio player, however with the current addition of pulse and jack, this is no longer supported. So it looks like sox is not being detected, then mplayer/mplayer2/mpv is found but not being correctly identified, hence the 'null' in the output. Anyway, installing sox will fix this as noted.
