### ISSUE TITLE
Warning messages under Xubuntu 20.04

### ISSUE THREAD

**Issue by Guybrush88** [salsaman/LiVES#9]
Opening LiVES 3.0.2 under Xubuntu 20.04, I get these error messages when opening it with a terminal:

Warning, frei0r plugin skipping blacklisted plugin Timeout indicator
LiVES info: Invalid effect farneback_analyserfarneback_analysersalsaman1 found in compound effect image_stabilizer, line 4

LiVES info: Invalid effect farneback_analyserfarneback_analysersalsaman1 found in compound effect motion_analyser, line 4

**Comment by salsaman** [comment]
Sorry for not responding earlier.
The first message no longer shows as a warning, it is purely informational.

The second no longer appears since I have patched farneback_analyser.
